"use client";

import { useLocale } from "@/components/providers/LocaleProvider";

/**
 * English for the admin panel's Bengali strings, keyed by the Bengali itself.
 *
 * The admin has hundreds of small labels — mostly tooltips in the Word-style
 * editor — that were written straight into the markup and so stayed Bengali
 * even with the panel switched to English. Naming a key for each of them would
 * have meant inventing three hundred names and touching every call site twice;
 * keying on the source string keeps the change to wrapping each literal, and
 * anything not listed here simply stays as it was rather than going blank.
 */
const EN: Record<string, string> = {
  // --- shared verbs and answers ---
  "ঠিক আছে": "OK",
  "বাতিল": "Cancel",
  "সংরক্ষণ": "Save",
  "যোগ করুন": "Add",
  "মুছে ফেলুন": "Delete",
  "বন্ধ করুন": "Close",
  "বেছে নিন": "Choose",
  "নেই": "None",
  "ডিফল্ট": "Default",
  "মোট": "total",
  "অন্যান্য": "Other",
  "লোড হচ্ছে…": "Loading…",
  "মোছা হচ্ছে…": "Deleting…",
  "শুরু হচ্ছে…": "Starting…",
  "আনা হচ্ছে…": "Loading…",
  "আপলোড ব্যর্থ": "Upload failed",
  "যোগ করা গেল না": "Could not add",
  "মুছতে পারা গেল না": "Could not delete",

  // --- alignment and direction ---
  "বাম": "Left",
  "মাঝ": "Centre",
  "ডান": "Right",
  "বামে": "Left",
  "মাঝে": "Centre",
  "ডানে": "Right",
  "জাস্টিফাই": "Justify",
  "অ্যালাইনমেন্ট": "Alignment",
  "লেখার দিক": "Text direction",
  "বাম → ডান": "Left to right",
  "ডান → বাম": "Right to left",
  "বাম → ডান (LTR)": "Left to right (LTR)",
  "ডান → বাম (RTL)": "Right to left (RTL)",

  // --- Home tab ---
  "পেস্ট (Ctrl+V)": "Paste (Ctrl+V)",
  "কাট (Ctrl+X)": "Cut (Ctrl+X)",
  "কপি (Ctrl+C)": "Copy (Ctrl+C)",
  "ফরম্যাট পেইন্টার — চাপুন, তারপর যেখানে বসাবেন সিলেক্ট করুন":
    "Format painter — press it, then select where to apply the formatting",
  "ফন্ট ডায়ালগ": "Font dialog",
  "ফন্ট সাইজ": "Font size",
  "ফন্ট বড় করুন": "Grow font",
  "ফন্ট ছোট করুন": "Shrink font",
  "ছোট/বড় হাতের অক্ষর": "Change case",
  "সব ফরম্যাট মুছুন": "Clear all formatting",
  "হাইলাইট": "Highlight",
  "হাইলাইট মুছুন": "Remove highlight",
  "ফন্টের রঙ": "Font colour",
  "স্বয়ংক্রিয় রঙ": "Automatic colour",
  "প্যারাগ্রাফ ডায়ালগ": "Paragraph dialog",
  "বুলেট তালিকা": "Bulleted list",
  "নম্বর তালিকা": "Numbered list",
  "চেকলিস্ট": "Checklist",
  "ইনডেন্ট কমান (Shift+Tab)": "Decrease indent (Shift+Tab)",
  "ইনডেন্ট বাড়ান (Tab)": "Increase indent (Tab)",
  "ইনডেন্ট কমান": "Decrease indent",
  "ইনডেন্ট বাড়ান": "Increase indent",
  "উদ্ধৃতি": "Quote",
  "লাইন ও প্যারা স্পেসিং": "Line and paragraph spacing",
  "লাইন স্পেসিং": "Line spacing",
  "প্যারার পরে ফাঁকা": "Space after paragraph",
  "খুঁজুন (Ctrl+F)": "Find (Ctrl+F)",
  "বদলান (Ctrl+H)": "Replace (Ctrl+H)",
  "সব সিলেক্ট করুন (Ctrl+A)": "Select all (Ctrl+A)",
  "পেস্ট করার ধরন": "Paste options",
  "ফরম্যাট সহ": "Keep formatting",
  "শুধু লেখা (ফরম্যাট ছাড়া)": "Text only (no formatting)",

  // --- Insert tab ---
  "টেবিল ডায়ালগ": "Table dialog",
  "টেবিল যোগ করুন": "Insert table",
  "টেবিল যোগ করুন…": "Insert table…",
  "উপরে সারি যোগ": "Insert row above",
  "নিচে সারি যোগ": "Insert row below",
  "সারি মুছুন": "Delete row",
  "হেডার সারি চালু/বন্ধ": "Toggle header row",
  "বামে কলাম যোগ": "Insert column left",
  "ডানে কলাম যোগ": "Insert column right",
  "কলাম মুছুন": "Delete column",
  "ঘর জোড়া / আলাদা করুন": "Merge or split cells",
  "পুরো টেবিল মুছুন": "Delete whole table",
  "ছবি — ক্যাপশন, কৃতিত্ব ও alt সহ":
    "Picture — with caption, credit and alt text",
  "YouTube ভিডিও বসান": "Insert a YouTube video",
  "লিংক (Ctrl+K)": "Link (Ctrl+K)",
  "বুকমার্ক — খবরের ভেতরে লাফ দেওয়ার জায়গা":
    "Bookmark — a place to jump to inside the story",
  "ফ্যাক্ট বক্স — খবরের পাশে আলাদা বাক্স":
    "Fact box — a separate panel beside the story",
  "ড্রপ ক্যাপ — অনুচ্ছেদের প্রথম অক্ষর বড়":
    "Drop cap — a large first letter for the paragraph",
  "বিভাজক রেখা": "Divider",
  "সিম্বল — ৳ ° ½ ইত্যাদি": "Symbol — ৳ ° ½ and so on",
  "ইমোজি": "Emoji",
  "ইকুয়েশন (LaTeX)": "Equation (LaTeX)",

  // --- Insert dialogs ---
  "ছবির সেটিংস": "Picture settings",
  "ছবি যোগ করুন": "Insert a picture",
  "ছবির URL": "Picture URL",
  "যেমন: রাজধানীর মিরপুরে নতুন উড়ালসড়ক":
    "e.g. New flyover opens in Mirpur, Dhaka",
  "ছবি: LinkNews24": "Photo: LinkNews24",
  "ছবিতে যা দেখা যাচ্ছে": "What the picture shows",
  "YouTube ভিডিও যোগ করুন": "Insert a YouTube video",
  "লিংক সম্পাদনা": "Edit link",
  "লিংক যোগ করুন": "Insert link",
  "বুকমার্ক (অ্যাংকর) বসান": "Insert a bookmark (anchor)",
  "যেমন: ঘটনার-বিবরণ": "e.g. what-happened",
  "ভগ্নাংশ": "Fraction",
  "বর্গমূল": "Square root",
  "যোগফল": "Sum",
  "শতকরা বৃদ্ধি": "Percentage increase",
  "ইকুয়েশন যোগ করুন": "Insert an equation",
  "ছবি": "Picture",
  "ক্যাপশন — ছবির নিচে ছাপা হবে": "Caption — printed under the picture",
  "ছবির কৃতিত্ব": "Picture credit",
  "Alt লেখা — SEO ও অন্ধ পাঠকের জন্য":
    "Alt text — for search engines and blind readers",
  "অবস্থান": "Position",
  "ভিডিওর লিংক": "Video link",
  "ঠিকানা": "Address",
  "নতুন ট্যাবে খুলবে": "Open in a new tab",
  "লিংক মুছে ফেলুন": "Remove link",
  "বুকমার্কের নাম": "Bookmark name",
  "নমুনা — চাপলে বসে যাবে": "Examples — click one to insert it",
  "সারি (rows)": "Rows",
  "কলাম (columns)": "Columns",
  "প্রথম সারিটি হেডার হবে": "Make the first row a header",
  "বামে, পাশে লেখা": "Left, text beside",
  "ডানে, পাশে লেখা": "Right, text beside",

  // --- Table tab ---
  "উপরে একটি সারি যোগ করুন": "Insert a row above",
  "উপরে সারি": "Row above",
  "নিচে একটি সারি যোগ করুন": "Insert a row below",
  "নিচে সারি": "Row below",
  "এই সারিটি মুছুন": "Delete this row",
  "বামে একটি কলাম যোগ করুন": "Insert a column to the left",
  "বামে কলাম": "Column left",
  "ডানে একটি কলাম যোগ করুন": "Insert a column to the right",
  "ডানে কলাম": "Column right",
  "এই কলামটি মুছুন": "Delete this column",
  "নির্বাচিত ঘরগুলো এক করুন": "Merge the selected cells",
  "জোড়া দিন": "Merge",
  "জোড়া ঘরটি আবার আলাদা করুন": "Split the merged cell again",
  "আলাদা করুন": "Split",
  "প্রথম সারিটি হেডার করুন / সরান": "Make the first row a header, or undo it",
  "হেডার সারি": "Header row",
  "প্রথম কলামটি হেডার করুন / সরান":
    "Make the first column a header, or undo it",
  "হেডার কলাম": "Header column",
  "পুরো টেবিলটি মুছে ফেলুন": "Delete the whole table",
  "টেবিল মুছুন": "Delete table",
  "পুরো টেবিলটি সিলেক্ট করুন": "Select the whole table",
  "সিলেক্ট": "Select",
  "টেবিলটি এক ধাপ উপরে নিন": "Move the table up one step",
  "উপরে সরান": "Move up",
  "টেবিলটি এক ধাপ নিচে নিন": "Move the table down one step",
  "নিচে সরান": "Move down",
  "টেবিলটি ধরে অন্য জায়গায় নিন": "Drag the table somewhere else",
  "টেবিলের আকার বদলাতে টানুন": "Drag to resize the table",
  "4 x 3 টেবিল": "4 × 3 table",
  "মাউস ঘুরিয়ে মাপ বাছুন": "Move the pointer to choose the size",

  // --- Layout tab ---
  "মাঝে, নিজের লাইনে": "Centred, on its own line",
  "বামে, চারপাশে লেখা": "Left, text wraps around",
  "ডানে, চারপাশে লেখা": "Right, text wraps around",
  "এক কলাম — স্বাভাবিক": "One column — normal",
  "বাছাই করা লেখাটি দুই কলামে সাজান":
    "Set the selected text in two columns",
  "বাছাই করা লেখাটি তিন কলামে সাজান":
    "Set the selected text in three columns",
  "হাইফেনেশন — লাইনের শেষে শব্দ ভাঙা":
    "Hyphenation — break words at the end of a line",
  "ছবির অবস্থান ও চারপাশে লেখা": "Picture position and text wrap",
  "আগে একটি ছবি সিলেক্ট করুন": "Select a picture first",
  "ছবির অবস্থান বদলাতে আগে খবরের ভেতরের একটি ছবিতে ক্লিক করুন।":
    "To move a picture, click one inside the story first.",
  "ছবির অবস্থান": "Picture position",
  "চওড়া": "Width",

  // --- Review tab and dialogs ---
  "শব্দ, অক্ষর, অনুচ্ছেদ ও পড়ার সময়":
    "Words, characters, paragraphs and reading time",
  "বানান পরীক্ষা চালু/বন্ধ": "Turn spell check on or off",
  "লেখা পড়ে শোনাবে — সিলেক্ট করা থাকলে শুধু সেটুকু":
    "Reads the text aloud — only the selection, if there is one",
  "মুখে বলুন, লেখা হয়ে যাবে (বাংলা)": "Speak and it types (Bengali)",
  "ছবিতে alt আছে কি না, শিরোনামের ক্রম ঠিক কি না — পরীক্ষা করুন":
    "Check that pictures have alt text and headings are in order",
  "শব্দ": "Words",
  "অক্ষর (ফাঁকা সহ)": "Characters (with spaces)",
  "অক্ষর (ফাঁকা ছাড়া)": "Characters (without spaces)",
  "অনুচ্ছেদ": "Paragraphs",
  "শিরোনাম": "Headings",
  "লিংক": "Links",
  "পড়তে লাগবে": "Reading time",
  "শব্দ গণনা": "Word count",
  "একটি শিরোনাম ফাঁকা।": "A heading is empty.",
  "খবরে কোনো ছবি নেই।": "The story has no pictures.",
  "কোনো উপশিরোনাম নেই — লম্বা লেখা ভাগ করলে পড়তে সুবিধা হয়।":
    "No sub-headings — breaking up a long piece makes it easier to read.",
  "অ্যাক্সেসিবিলিটি পরীক্ষা": "Accessibility check",
  "পড়ার সময় বাংলা সংবাদের গড় গতি — মিনিটে ১৮০ শব্দ — ধরে হিসাব করা।":
    "Reading time assumes the average pace for Bengali news — 180 words a minute.",
  "কোনো সমস্যা পাওয়া যায়নি — খবরটি প্রকাশের জন্য প্রস্তুত।":
    "Nothing found — the story is ready to publish.",

  // --- View tab, title bar, outline ---
  "পেজ ভিউ — Word-এর মতো সাদা কাগজে": "Page view — white paper, as in Word",
  "ওয়েব ভিউ — সাইটে যে প্রস্থে দেখাবে":
    "Web view — the width it will have on the site",
  "জুম": "Zoom",
  "জুম কমান": "Zoom out",
  "জুম বাড়ান": "Zoom in",
  "ডকুমেন্ট আউটলাইন — শিরোনামের তালিকা":
    "Document outline — the list of headings",
  "ফুল স্ক্রিন (Esc দিয়ে বেরোন)": "Full screen (Esc to leave)",
  "খসড়া সেভ করুন (Ctrl+S)": "Save draft (Ctrl+S)",
  "আন্ডু (Ctrl+Z)": "Undo (Ctrl+Z)",
  "রিডু (Ctrl+Y)": "Redo (Ctrl+Y)",
  "খুঁজুন ও বদলান (Ctrl+F)": "Find and replace (Ctrl+F)",
  "প্রিন্ট (Ctrl+P)": "Print (Ctrl+P)",
  "(শিরোনামহীন)": "(untitled)",
  "আউটলাইন": "Outline",
  "কোনো শিরোনাম নেই। স্টাইল গ্যালারি থেকে শিরোনাম দিলে এখানে দেখা যাবে।":
    "No headings yet. Apply one from the style gallery and it will appear here.",
  "এখানে লিখুন…": "Write here…",
  "নতুন আর্টিকেল": "New article",
  "রিবন গুটিয়ে ফেলুন": "Collapse the ribbon",
  "রিবন দেখান": "Show the ribbon",

  // --- find & replace ---
  "যা খুঁজবেন…": "Find what…",
  "যা বসাবেন…": "Replace with…",
  "আগেরটি (Shift+Enter)": "Previous (Shift+Enter)",
  "পরেরটি (Enter)": "Next (Enter)",
  "বন্ধ করুন (Esc)": "Close (Esc)",
  "বদলান": "Replace",
  "সব বদলান": "Replace all",
  "ছোট/বড় হাতের মিল": "Match case",
  "পুরো শব্দ": "Whole word",

  // --- style gallery ---
  "¶ সাধারণ": "¶ Normal",
  "¶ ফাঁকা ছাড়া": "¶ No spacing",
  "গাঢ়": "Bold",
  "তির্যক": "Italic",
  "কোড": "Code",

  // --- font picker ---
  "ফন্ট": "Font",
  "সাইজ": "Size",
  "সাইটের নিজের ফন্ট — সব পাঠক দেখবে":
    "The site's own fonts — every reader sees these",
  "বাংলা — পাঠকের কম্পিউটারে থাকলে দেখাবে":
    "Bengali — shown only if the reader has the font",
  "ইংরেজি — পাঠকের কম্পিউটারে থাকলে দেখাবে":
    "Latin — shown only if the reader has the font",
  "＋ এই কম্পিউটারের সব ফন্ট আনুন": "＋ Load every font on this computer",
  "Default (সাইটের ফন্ট)": "Default (site font)",
  "স্টাইল ও ইফেক্ট": "Style and effects",
  "প্রিভিউ": "Preview",
  "আমার সোনার বাংলা — AaBbCcD": "The quick brown fox — AaBbCcD",
  "প্যারাগ্রাফ": "Paragraph",
  "ইনডেন্ট (ধাপ)": "Indent (steps)",

  // --- symbol picker ---
  "টাকা ও মুদ্রা": "Taka and currency",
  "বাংলা সংখ্যা": "Bengali numerals",
  "গণিত": "Maths",
  "বিরাম ও চিহ্ন": "Punctuation and marks",
  "তীর ও অন্যান্য": "Arrows and others",
  "মুখভঙ্গি": "Faces",
  "খবর ও কাজ": "News and work",
  "খেলা ও আবহাওয়া": "Sport and weather",

  // --- clipboard ---
  "আগে লেখা সিলেক্ট করুন": "Select some text first",
  "কাট হয়েছে": "Cut",
  "কপি হয়েছে": "Copied",
  "পেস্ট হয়েছে": "Pasted",
  "সাইটে HTTPS নেই বলে ব্রাউজার পেস্ট আটকে দিচ্ছে — Ctrl+V চাপুন":
    "The browser blocks pasting without HTTPS — press Ctrl+V instead",
  "ব্রাউজার অনুমতি দেয়নি — Ctrl+V চাপুন":
    "The browser refused — press Ctrl+V instead",

  // --- translation bar ---
  "এই ব্রাউজারে অনুবাদ সুবিধাটি নেই।":
    "This browser has no built-in translator.",
  "অনুবাদ করা যায়নি। আবার চেষ্টা করুন।":
    "The translation failed. Please try again.",
  "আগে বাংলায় শিরোনাম ও লেখা দিন":
    "Write the Bengali headline and body first",
  "প্রথমবার ভাষা প্যাক নামবে (একবারই)":
    "The language pack downloads the first time (once only)",
  "এটি যন্ত্রে করা অনুবাদ — প্রকাশের আগে পড়ে দেখুন":
    "This is a machine translation — read it before publishing",
  "দেখেছি": "Got it",

  // --- categories page ---
  "মূল মেনুতে ফিরিয়ে নিন": "Move back to the main menu",
  "বের করুন": "Move out",
  "সাব-ক্যাটাগরি": "Sub-category",
  "এই ক্যাটাগরিতে কোনো আর্টিকেল নেই। মুছে ফেলবেন?":
    "This category holds no articles. Delete it?",
  "অন্য ক্যাটাগরিতে সরিয়ে নিন": "Move them to another category",
  "আর্টিকেলগুলো থেকে যাবে, শুধু ক্যাটাগরিটা বদলাবে।":
    "The articles stay; only their category changes.",
  "ক্যাটাগরি বাছুন…": "Choose a category…",
  "সরিয়ে মুছুন": "Move, then delete",
  "আর্টিকেলসহ মুছে ফেলুন": "Delete with the articles",
  "ফেরত আনা যাবে না।": "This cannot be undone.",

  // --- admin shell and pages ---
  "ফন্ট ছোট": "Smaller text",
  "ফন্ট বড": "Larger text",
  "ফন্ট বড়": "Larger text",
  "অ−": "A−",
  "অ+": "A+",
  "লাইভ টিভি": "Live TV",
  "নাম, ইমেইল ও কমপক্ষে ৬ অক্ষরের পাসওয়ার্ড দিন":
    "Enter a name, an email and a password of at least 6 characters",
  // --- longer prose and remaining labels ---
  "আপলোড": "Upload",
  "অন্য রঙ…": "Other colour…",
  "সেগুলোর কী হবে?": "What should happen to them?",
  "চওড়া — {n}%": "Width — {n}%",
  "এই কম্পিউটারে ইনস্টল করা ({n})": "Installed on this computer ({n})",
  "অনুমতি পাওয়া যায়নি। ঠিকানা বারের 🔒 আইকনে গিয়ে ফন্টের অনুমতি দিন, তারপর আবার চেষ্টা করুন।":
    "Permission was refused. Allow fonts from the 🔒 icon in the address bar, then try again.",
  "কম্পিউটারে ইনস্টল করা ফন্ট আনার সুবিধাটি Chrome/Edge ডেস্কটপে পাওয়া যায়।":
    "Reading the computer’s installed fonts works in Chrome and Edge on the desktop.",
  "YouTube-এর সাধারণ লিংক বা youtu.be দুটোই চলবে। ভিডিওটি খবরের ভেতরে বসে যাবে, পাঠক সেখানেই দেখতে পারবে।":
    "An ordinary YouTube link or a youtu.be one both work. The video sits inside the story and plays there.",
  "এই অনুচ্ছেদে একটি নাম বসবে, যাতে খবরের ভেতরেই সরাসরি এখানে লিংক করা যায় — লম্বা প্রতিবেদনে কাজে লাগে।":
    "This paragraph gets a name, so the story can link straight to it — useful in a long report.",
  "লাল = ঠিক করা দরকার · হলুদ = ভেবে দেখুন। alt লেখা যোগ করতে ছবিতে ক্লিক করে Insert → Picture খুলুন।":
    "Red = must fix · amber = worth a look. To add alt text, click the picture and open Insert → Picture.",
  "টেবিলের উপরে-বাঁয়ের ⊞ ধরে টানলে টেবিলটি অন্য জায়গায় যাবে, নিচে-ডানের কোণা ধরে টানলে আকার বদলাবে, আর দুই কলামের মাঝের দাগ টানলে কলামের চওড়া বদলাবে।":
    "Drag the ⊞ at the top left to move the table, the bottom-right corner to resize it, and the line between two columns to change a column width.",
  "মিনিট": "min",
  "এখানে": "here",
  "এখানে ক্লিক": "click here",
  "ক্লিক করুন": "click",
  "-এর ভেতরে — নাম (বাংলা)": " — name inside (Bengali)",
  "কপি করা গেল না — Ctrl+C চাপুন": "Could not copy — press Ctrl+C",
  "কপি করা গেল না — Ctrl+X চাপুন": "Could not cut — press Ctrl+X",
  "০টি": "0",
  "শিরোনামহীন": "untitled",
  "ডেটা লোড করা যায়নি": "Could not load the data",
  "কয়েক সেকেন্ডে আবার চেষ্টা হচ্ছে…": "trying again in a few seconds…",
  "টি অনুমোদনের অপেক্ষায়": " awaiting approval",
  "টি আর্টিকেল": " articles",
  "এই ক্যাটাগরিতে": "This category holds",
  "আছে।": ".",
  "টি আর্টিকেল ও সেগুলোর সব কমেন্ট চিরতরে মুছে যাবে।":
    " articles and all their comments will be gone for good.",
  "আর্টিকেলসহ মুছুন": "Delete with articles",
  "বাংলা": "Bengali",
  "ভাষা প্যাক নামছে… {n}%": "Downloading the language pack… {n}%",
  "অনুবাদ হচ্ছে… {a}/{b}": "Translating… {a}/{b}",
  "শব্দ:": "Words:",
  "অক্ষর:": "Characters:",
  "পড়তে ~": "≈",
  "বসবে:": "Inserts:",
  "টেবিল": "table",
  "৳": "BDT ",
  "শিরোনাম {a} থেকে সরাসরি {b}-এ লাফ দিয়েছে — মাঝের ধাপ বাদ পড়েছে।":
    "Heading {a} jumps straight to {b} — a level is missing in between.",
  "“{a}” লেখা লিংক — কোথায় নিয়ে যাবে তা বোঝা যায় না।":
    "A link reading “{a}” — there is no telling where it goes.",
  "{n}টি ছবিতে alt লেখা নেই — অন্ধ পাঠক ও Google কিছুই বুঝবে না।":
    "{n} pictures have no alt text — neither blind readers nor Google can tell what they show.",
  "স্বয়ংক্রিয় অনুবাদ চলে Chrome ১৩৮+ (ডেস্কটপ)-এ। ইংরেজি ঘরগুলো হাতে লিখতে হবে।":
    "Automatic translation needs Chrome 138+ on the desktop. Otherwise fill the English fields by hand.",
  "বাংলা থেকে ইংরেজি করুন": "Translate Bengali to English",
  "বিশেষ করে নাম, সংখ্যা ও উদ্ধৃতি মিলিয়ে নিন। আটক/গ্রেপ্তার, অভিযুক্ত/দোষী — এই শব্দগুলো ঠিক আছে কি না দেখুন।":
    "Check names, numbers and quotations especially. Watch words like detained/arrested and accused/guilty.",
  "এই কম্পিউটারে বাংলা ভয়েস ইন্সটল করা নেই, তাই বাংলা অংশটুকু পড়া যাচ্ছে না। Windows Settings → Time & language → Speech → Manage voices → Add voices থেকে বাংলা যোগ করলে এখানেই কাজ করবে।":
    "This computer has no Bengali voice installed, so the Bengali cannot be read aloud. Add one from Windows Settings → Time & language → Speech → Manage voices → Add voices and it will work here.",
  "¶ শিরোনাম {n}": "¶ Heading {n}",
  // --- permissions, approvals and the team page ---
  "বাতিল হয়েছে": "Rejected",
  "মডিউল": "Module",
  "সব বন্ধ": "All off",
  "সব চালু": "All on",
  "কাস্টম": "Custom",
  "রোলের মতো করুন": "Match role",
  "দেখা": "View",
  "এডিট": "Edit",
  "ডিলিট": "Delete",
  "অনুমতি": "Permissions",
  "সুপার অ্যাডমিনের সব অনুমতি সবসময় থাকে": "The Super Admin always has every permission",
  "রোল": "Role",
  "এখানে বদলালে শুধু এই ব্যক্তির জন্য আলাদা (কাস্টম) অনুমতি হবে।": "Changes here apply to this person only, as custom permissions.",
  "সংরক্ষিত": "Saved",
  "সব রোলের মতো করুন": "Reset all to role",
  "কোন রোল কোন মডিউল দেখতে, এডিট করতে বা মুছতে পারবে তা এখান থেকে ঠিক করুন। কোনো একজনের জন্য আলাদা অনুমতি দিতে ইউজার পাতায় যান।": "Decide which modules each role can view, edit or delete. To give one person their own permissions, go to the Users page.",
  "সব অনুমতি সবসময় — বদলানো যায় না": "Every permission, always — cannot be changed",
  "জন": "people",
  "পরিবর্তন সাথে সাথে কার্যকর হয় — এই রোলের সবার প্যানেল তৎক্ষণাৎ বদলে যায়। সুপার অ্যাডমিন ছাড়া সবার খবর প্রকাশের আগে অনুমোদনে যায়।": "Changes apply instantly — everyone with this role sees their panel update at once. Stories from anyone but the Super Admin go for approval before publishing.",
  "ডিফল্টে ফেরান": "Reset to default",
  "ডিফল্টে ফেরাবেন?": "Reset to default?",
  "এই রোলের সব অনুমতি শুরুর অবস্থায় ফিরে যাবে।": "Every permission for this role will go back to its starting setting.",
  "ফেরান": "Reset",
  "কখনো আসেননি": "Never signed in",
  "এইমাত্র": "just now",
  "মিনিট আগে": "min ago",
  "ঘণ্টা আগে": "h ago",
  "দিন আগে": "d ago",
  "নাম, সঠিক ইমেইল ও কমপক্ষে ৮ অক্ষরের পাসওয়ার্ড দিন": "Enter a name, a valid email and a password of at least 8 characters",
  "অনলাইনে": "Online",
  "সব অনুমতি": "All permissions",
  "অনুমোদিত — সাইটে প্রকাশিত হয়েছে": "Approved — now live on the site",
  "বাতিল করা হয়েছে — লেখককে জানানো হয়েছে": "Rejected — the writer has been notified",
  "খসড়ায় রাখা হয়েছে — লেখককে জানানো হয়েছে": "Moved to drafts — the writer has been notified",
  "টিমের পাঠানো খবর ও সংশোধন এখানে আসে। অনুমোদন দিলে সাথে সাথে সাইটে যাবে; বাতিল করলে লেখক নোটিফিকেশন পাবেন।": "Stories and edits from the team arrive here. Approving puts them on the site at once; rejecting notifies the writer.",
  "লাইভ আপডেট": "Live updates",
  "অনুমোদনের অপেক্ষায় কোনো খবর নেই": "No stories waiting for approval",
  "ব্রেকিং": "Breaking",
  "হিরো": "Hero",
  "ফিচার্ড": "Featured",
  "অনুমোদনের অপেক্ষায় কোনো সংশোধন নেই": "No edits waiting for approval",
  "লাইভ খবরে পরিবর্তন": "Edit to a live story",
  "নতুন শিরোনাম": "New headline",
  "লাইভ সংস্করণ দেখুন": "See the live version",
  "পরিবর্তন দেখুন": "See changes",
  "এখনো কোনো সিদ্ধান্ত নেওয়া হয়নি": "No decisions yet",
  "সংশোধন": "Edit",
  "নতুন খবর": "New story",
  "অনুমোদিত": "Approved",
  "খসড়ায় ফেরত": "Sent back to drafts",
  "খসড়ায় রাখুন": "Move to drafts",
  "বাতিল করুন": "Reject",
  "হচ্ছে…": "Working…",
  "অনুমোদন ও প্রকাশ": "Approve & publish",
  "খবরটি বাতিল করবেন?": "Reject this story?",
  "খসড়ায় ফেরত পাঠাবেন?": "Send back to drafts?",
  "কারণ (লেখক নোটিফিকেশনে দেখবেন)": "Reason (the writer sees this in their notification)",
  "যেমন: সূত্র যাচাই করা দরকার, শিরোনাম বদলান…": "e.g. sources need checking, change the headline…",
  "সারসংক্ষেপ": "Summary",
  "ক্যাটাগরি": "Category",
  "ট্যাগ": "Tags",
  "ব্রেকিং / হিরো / ফিচার্ড": "Breaking / Hero / Featured",
  "পরিবর্তন মিলিয়ে দেখুন": "Compare changes",
  "এখন সাইটে": "On the site now",
  "প্রস্তাবিত": "Proposed",
  "মূল লেখা": "Body",
  "বদলেছে": "Changed",
  "অপরিবর্তিত": "Unchanged",
  "অনুমোদন দিন": "Approve",
  "প্রকাশিত খবরের সংশোধন": "Edits to live stories",
  "সাম্প্রতিক সিদ্ধান্ত": "Recent decisions",
  "এইমাত্র এসেছেন": "just arrived",
  "মিনিট ধরে": "min",
  "ঘণ্টা": "h",
  "নতুন খবর লিখছেন": "Writing a new story",
  "খবর এডিট করছেন": "Editing a story",
  "(শিরোনাম নেই)": "(no headline)",
  "কে এখন প্যানেলে আছেন, কোন পাতায় কাজ করছেন, আর কে কতটি খবর দিয়েছেন।": "Who is in the panel now, which page they are working on, and how many stories each person has filed.",
  "এখন অনলাইনে": "Online now",
  "এই মুহূর্তে কেউ প্যানেলে নেই": "Nobody is in the panel right now",
  "প্যানেল খুলছেন…": "Opening the panel…",
  "কে কতটি খবর দিয়েছেন": "Stories filed by each person",
  "সদস্য": "Member",
  "আজ": "Today",
  "৭ দিনে": "7 days",
  "প্রকাশিত": "Published",
  "অপেক্ষায়": "Waiting",
  "শেষ কাজ": "Last activity",
  "সাম্প্রতিক কার্যকলাপ": "Recent activity",
  "এখনো কোনো কার্যকলাপ নেই": "No activity yet",
  "অজানা": "Unknown",
  "খসড়া খবর তৈরি করেছেন": "created a draft story",
  "অনুমোদনের জন্য খবর পাঠিয়েছেন": "sent a story for approval",
  "খবর সম্পাদনা করেছেন": "edited a story",
  "প্রকাশিত খবরে সংশোধন পাঠিয়েছেন": "sent an edit to a live story",
  "খবর অনুমোদন দিয়েছেন": "approved a story",
  "খবর প্রকাশ করেছেন": "published a story",
  "খবর সরিয়ে নিয়েছেন": "unpublished a story",
  "খবর বাতিল করেছেন": "rejected a story",
  "খবর খসড়ায় ফেরত পাঠিয়েছেন": "sent a story back to drafts",
  "খবর মুছেছেন": "deleted a story",
  "সংশোধন অনুমোদন দিয়েছেন": "approved an edit",
  "সংশোধন বাতিল করেছেন": "rejected an edit",
  "পরিবর্তন করেছেন": "made changes",
  "মুছেছেন": "deleted something",
  "লগইন করেছেন": "signed in",
  "লগআউট করেছেন": "signed out",
  "অনুমতি বদলেছেন": "changed permissions",
  "রোলের অনুমতি ডিফল্টে ফিরিয়েছেন": "reset a role's permissions",
  "নতুন ইউজার যোগ করেছেন": "added a user",
  "ইউজারের রোল বদলেছেন": "changed a user's role",
  "ইউজার নিষ্ক্রিয় করেছেন": "deactivated a user",
  "ইউজার মুছেছেন": "deleted a user",
  "পাসওয়ার্ড বদলেছেন": "changed their password",
  "ইমেইল বদলেছেন": "changed their email",
  "আজ লেখা খবর": "Stories today",
  "গত ৭ দিনে": "Last 7 days",
  "অনুমোদনের অপেক্ষায়": "Awaiting approval",
  "পরিবর্তন অনুমোদনে পাঠান": "Send changes for approval",
  "অনুমোদনের জন্য পাঠান": "Send for approval",
  "আপনার খবর সুপার অ্যাডমিনের অনুমোদনের পর সাইটে প্রকাশিত হবে।": "Your story will go live once the Super Admin approves it.",
  "এই খবরের একটি সংশোধন অনুমোদনের অপেক্ষায় আছে": "An edit to this story is waiting for approval",
  "অনুমোদন পাতায় দেখুন": "Open approvals",
  "আপনার পাঠানো সংশোধন অনুমোদনের অপেক্ষায় — নিচে সেটাই দেখানো হচ্ছে। আবার পাঠালে আগের প্রস্তাবের জায়গা নেবে।": "Your edit is waiting for approval — it is what you see below. Sending again replaces it.",
  "অন্য একজনের সংশোধন অপেক্ষায় আছে": "Someone else's edit is waiting",
  "আপনি পাঠালে সেটির জায়গা নেবে।": "Sending yours will replace it.",
  "খবরটি সুপার অ্যাডমিনের অনুমোদনের অপেক্ষায় আছে।": "This story is waiting for the Super Admin's approval.",
  "খবরটি বাতিল করা হয়েছে": "This story was rejected",
  "প্রয়োজনীয় সংশোধন করে আবার অনুমোদনের জন্য পাঠাতে পারেন।": "Make the changes needed and send it for approval again.",
  "সুপার অ্যাডমিন খসড়ায় ফেরত পাঠিয়েছেন": "The Super Admin sent this back to drafts",
  "এটি প্রকাশিত খবর। আপনার পরিবর্তন সুপার অ্যাডমিনের অনুমোদনের পর সাইটে যাবে; ততক্ষণ পাঠকেরা আগের সংস্করণ দেখবেন।": "This story is live. Your changes reach the site once the Super Admin approves them; until then readers see the current version.",
  "সুপার অ্যাডমিনের কাছে অনুমোদনের জন্য পাঠানো হয়েছে। সিদ্ধান্ত হলে নোটিফিকেশন পাবেন।": "Sent to the Super Admin for approval. You will be notified of the decision.",
  "শুধু আমার খবর": "Only my stories",
  "খসড়ায় নিন": "Move to drafts",
  "প্রকাশ করুন": "Publish",
  "সংশোধন অপেক্ষায়": "Edit pending",
  "আপনার জন্য": "For you",
  "সব পড়া হয়েছে": "Mark all read",
  "আপনার খবর অনুমোদিত ও প্রকাশিত হয়েছে": "Your story was approved and published",
  "আপনার সংশোধন অনুমোদিত হয়েছে": "Your edit was approved",
  "আপনার খবর বাতিল করা হয়েছে": "Your story was rejected",
  "আপনার সংশোধন বাতিল করা হয়েছে": "Your edit was rejected",
  "আপনার খবর খসড়ায় ফেরত পাঠানো হয়েছে": "Your story was sent back to drafts",
  "খবর অনুমোদনের অপেক্ষায়": "stories awaiting approval",
  "অনুমোদনের অপেক্ষায় কিছু নেই": "Nothing waiting for approval",
  "আজ জমা": "filed today",
  "এডিট করছেন": "Editing",
  "ড্যাশবোর্ড": "Dashboard",
  "আমার কাজ": "My work",
  "আজ লিখেছেন": "Written today",
  "খসড়া": "Drafts",
  "এই পাতা দেখার অনুমতি নেই": "You do not have access to this page",
  "সুপার অ্যাডমিন আপনাকে এই অংশের অনুমতি দেননি। দরকার হলে তাঁর সঙ্গে যোগাযোগ করুন।": "The Super Admin has not given you access to this section. Ask them if you need it.",
  "ড্যাশবোর্ডে ফিরুন": "Back to the dashboard",
  "সাইটের ভিজিটর ও পরিসংখ্যান দেখা": "Site visitors and statistics",
  "খবর লেখা, সম্পাদনা ও মোছা — প্রকাশের আগে অনুমোদন লাগবে": "Write, edit and delete stories — publishing needs approval",
  "ক্যাটাগরি ও ট্যাগ তৈরি, সাজানো ও মোছা": "Create, arrange and delete categories and tags",
  "ব্রেকিং নিউজের টিকার": "The breaking news ticker",
  "হোমপেজের সেকশন ও খবরের ক্রম": "Homepage sections and story order",
  "লাইভ টিভির লিংক ও চালু/বন্ধ": "Live TV link and on/off",
  "ছবি ও ফাইলের লাইব্রেরি": "Image and file library",
  "ই-পেপারের সংস্করণ আপলোড": "E-paper editions",
  "আইনজীবীর আবেদন যাচাই ও তালিকা": "Review and list lawyers",
  "রক্তদাতার আবেদন যাচাই ও তালিকা": "Review and list blood donors",
  "হাসপাতালের আবেদন যাচাই ও তালিকা": "Review and list hospitals",
  "নিউজলেটারের গ্রাহক তালিকা": "Newsletter subscribers",
  "বিজ্ঞাপন অনুমোদন ও রিপোর্ট": "Ad approval and reports",
  "পাঠকের মন্তব্য অনুমোদন ও মোছা": "Approve and delete reader comments",
  "সার্চ ইঞ্জিন ও সোশ্যাল শেয়ারের সেটিং": "Search engine and social sharing settings",
  "সাইটের লোগো, ফুটার ও সাধারণ সেটিং": "Site logo, footer and general settings",
  "কনটেন্ট": "Content",
  "সেবা ডিরেক্টরি": "Service directories",
  "সাইট পরিচালনা": "Site management",
  "এই পাতায়": "On this page",
  // --- breaking bar, social links, logo ---
  "ব্রেকিং বার চালু আছে": "The breaking bar is on",
  "ব্রেকিং বার বন্ধ আছে": "The breaking bar is off",
  "সাইটের হেডারে এখন": "The site header is now running",
  "টি লাইন চলছে।": "line(s).",
  "পাঠকেরা কোনো ব্রেকিং বার দেখছেন না। নিচের খবরগুলো রাখা আছে — চালু করলেই আবার দেখাবে।": "Readers see no breaking bar. The lines below are kept — switch it on and they show again.",
  "পুরো ব্রেকিং বার চালু/বন্ধ": "Breaking bar on/off",
  "ব্রেকিং খবর": "Breaking stories",
  "আর্টিকেলে 'ব্রেকিং' চালু করা প্রকাশিত খবর। সুইচ বন্ধ করলে খবরটি বার থেকে সরে যাবে, খবর নিজে থাকবে।": "Published stories with 'breaking' switched on. Turning the switch off takes the story off the bar; the story itself stays.",
  "কোনো খবরে ব্রেকিং চালু নেই": "No story is marked breaking",
  "সাইটে দেখুন": "View on site",
  "ব্রেকিং থেকে সরান": "Remove from breaking",
  "নিজে লেখা লাইন": "Typed lines",
  "খবর ছাড়াই ছোট একটি লাইন বারে দেখাতে চাইলে এখানে লিখুন।": "Write a short line here to show it on the bar without a story.",
  "কোনো সোশ্যাল লিংক নেই — নিচের বাটনে যোগ করুন": "No social links yet — add one below",
  "লিংক https:// দিয়ে শুরু হতে হবে": "Links must start with https://",
  "সোশ্যাল মিডিয়া": "Social network",
  "ওয়েবসাইট": "Website",
  "উপরে": "Up",
  "নিচে": "Down",
  "সোশ্যাল লিংক যোগ করুন": "Add social link",
  "ফুটারে যেমন দেখাবে": "In the footer",
  "PNG, JPG বা WEBP ছবি দিন": "Use a PNG, JPG or WEBP image",
  "আপলোড হচ্ছে…": "Uploading…",
  "নতুন লোগো আপলোড": "Upload new logo",
  "আগের লোগোতে ফিরুন": "Back to the original logo",
  "চওড়া (আড়াআড়ি) লোগো ভালো দেখায়, স্বচ্ছ ব্যাকগ্রাউন্ডের PNG হলে সবচেয়ে ভালো। সংরক্ষণ করলে হেডার ও ফুটারে সাথে সাথে বদলাবে।": "A wide (landscape) logo works best, ideally a PNG with a transparent background. Saving changes the header and footer at once.",
  "সাইটের লোগো": "Site logo",
};

/** Fills {name} placeholders after translating. */
export function fill(text: string, vars: Record<string, string | number>) {
  let out = text;
  for (const k of Object.keys(vars)) out = out.replace(`{${k}}`, String(vars[k]));
  return out;
}

/** Translate one admin string for a known locale. */
export function adminText(bn: string, locale: "bn" | "en"): string {
  return locale === "en" ? EN[bn] ?? bn : bn;
}

/** The hook every admin component uses: `ax("বোল্ড")`. */
export function useAdminText() {
  const { locale } = useLocale();
  return (bn: string) => adminText(bn, locale);
}
