import type { Article, Category } from "@/types/content";

export const categories: Category[] = [
  { id: "national", name: "জাতীয়", slug: "national" },
  { id: "politics", name: "রাজনীতি", slug: "politics" },
  { id: "world", name: "আন্তর্জাতিক", slug: "world" },
  { id: "business", name: "অর্থনীতি", slug: "business" },
  { id: "sports", name: "খেলা", slug: "sports" },
  { id: "entertainment", name: "বিনোদন", slug: "entertainment" },
  { id: "technology", name: "প্রযুক্তি", slug: "technology" },
  { id: "health", name: "স্বাস্থ্য", slug: "health" },
  { id: "education", name: "শিক্ষা", slug: "education" },
  { id: "opinion", name: "মতামত", slug: "opinion" },
  { id: "religion", name: "ধর্ম", slug: "religion" },
  { id: "crime", name: "আইন-আদালত", slug: "crime" },
  { id: "environment", name: "পরিবেশ", slug: "environment" },
  { id: "lifestyle", name: "লাইফস্টাইল", slug: "lifestyle" },
  { id: "video", name: "ভিডিও", slug: "video" },
];

const findCategory = (slug: string): Category =>
  categories.find((c) => c.slug === slug)!;

export const breakingNewsItems: string[] = [
  "ঢাকায় মেট্রোরেলের নতুন লাইন উদ্বোধন করলেন সংশ্লিষ্ট কর্তৃপক্ষ",
  "জাতীয় বাজেট নিয়ে সংসদে আলোচনা শুরু",
  "উপকূলীয় অঞ্চলে ঘূর্ণিঝড় সতর্কতা জারি, সরে যাচ্ছে হাজারো মানুষ",
];

export const heroArticle: Article = {
  id: "hero-1",
  title: "রাজধানীতে নতুন এক্সপ্রেসওয়ে প্রকল্পের কাজ শুরু, যানজট কমার আশা",
  slug: "capital-expressway-project-begins",
  excerpt:
    "নগর পরিকল্পনাবিদদের মতে, প্রকল্পটি সম্পন্ন হলে রাজধানীর পূর্ব-পশ্চিম সংযোগে যাতায়াতের সময় উল্লেখযোগ্যভাবে কমে আসবে।",
  category: findCategory("national"),
  author: "স্টাফ করেসপন্ডেন্ট",
  publishedAt: "২ ঘণ্টা আগে",
  imageTone: "navy",
  isBreaking: true,
};

export const nationalArticles: Article[] = [
  {
    id: "nat-1",
    title: "বন্যা পরিস্থিতির উন্নতি, ঘরে ফিরছে ক্ষতিগ্রস্ত পরিবারগুলো",
    slug: "flood-situation-improves",
    excerpt: "ত্রাণ কার্যক্রম অব্যাহত রয়েছে জেলা প্রশাসনের তত্ত্বাবধানে।",
    category: findCategory("national"),
    author: "নিজস্ব প্রতিবেদক",
    publishedAt: "৪ ঘণ্টা আগে",
    imageTone: "slate",
  },
  {
    id: "nat-2",
    title: "সরকারি হাসপাতালে বিনামূল্যে স্বাস্থ্যসেবা কর্মসূচি সম্প্রসারণ",
    slug: "free-healthcare-program-expansion",
    excerpt: "প্রান্তিক জনগোষ্ঠীর জন্য নতুন সুবিধা যুক্ত হয়েছে কর্মসূচিতে।",
    category: findCategory("national"),
    author: "স্বাস্থ্য প্রতিবেদক",
    publishedAt: "৫ ঘণ্টা আগে",
    imageTone: "amber",
  },
  {
    id: "nat-3",
    title: "গ্রামীণ সড়ক উন্নয়ন প্রকল্পে বরাদ্দ বাড়াল পরিকল্পনা মন্ত্রণালয়",
    slug: "rural-road-development-budget",
    excerpt: "আগামী অর্থবছরে দেশজুড়ে প্রায় দুই হাজার কিলোমিটার সড়ক সংস্কার হবে।",
    category: findCategory("national"),
    author: "অর্থনৈতিক প্রতিবেদক",
    publishedAt: "৭ ঘণ্টা আগে",
    imageTone: "navy",
  },
  {
    id: "nat-4",
    title: "শীতের শুরুতেই রাজধানীতে বায়ুদূষণ বৃদ্ধি, সতর্ক থাকার পরামর্শ",
    slug: "air-pollution-rises-in-capital",
    excerpt: "পরিবেশ অধিদপ্তর জানিয়েছে বায়ুমান সূচক ঝুঁকিপূর্ণ পর্যায়ে পৌঁছেছে।",
    category: findCategory("national"),
    author: "পরিবেশ প্রতিবেদক",
    publishedAt: "৮ ঘণ্টা আগে",
    imageTone: "slate",
  },
];

export const politicsArticles: Article[] = [
  {
    id: "pol-1",
    title: "আসন্ন নির্বাচন নিয়ে দলগুলোর মধ্যে আলোচনা অব্যাহত",
    slug: "election-discussions-continue",
    excerpt: "নির্বাচন কমিশনের সঙ্গে বৈঠকের পর নতুন সময়সূচি প্রকাশ।",
    category: findCategory("politics"),
    author: "রাজনৈতিক প্রতিবেদক",
    publishedAt: "৩ ঘণ্টা আগে",
    imageTone: "crimson",
  },
  {
    id: "pol-2",
    title: "সংসদে পাস হলো নতুন তথ্য সুরক্ষা বিল",
    slug: "data-protection-bill-passed",
    excerpt: "বিলটি নাগরিকদের ডিজিটাল তথ্যের সুরক্ষা নিশ্চিত করবে বলে জানানো হয়েছে।",
    category: findCategory("politics"),
    author: "সংসদ প্রতিবেদক",
    publishedAt: "৬ ঘণ্টা আগে",
    imageTone: "navy",
  },
  {
    id: "pol-3",
    title: "স্থানীয় সরকার নির্বাচনের তফসিল ঘোষণা",
    slug: "local-government-election-schedule",
    excerpt: "আগামী মাসে দেশের ৬৪ জেলায় পর্যায়ক্রমে ভোটগ্রহণ অনুষ্ঠিত হবে।",
    category: findCategory("politics"),
    author: "নিজস্ব প্রতিবেদক",
    publishedAt: "৯ ঘণ্টা আগে",
    imageTone: "slate",
  },
  {
    id: "pol-4",
    title: "প্রধান বিরোধী দলের সংবাদ সম্মেলন আজ",
    slug: "opposition-press-conference-today",
    excerpt: "সাম্প্রতিক ইস্যু নিয়ে প্রতিক্রিয়া জানাবে দলটি বলে সূত্রে জানা গেছে।",
    category: findCategory("politics"),
    author: "রাজনৈতিক প্রতিবেদক",
    publishedAt: "১০ ঘণ্টা আগে",
    imageTone: "crimson",
  },
];

export const sportsArticles: Article[] = [
  {
    id: "spo-1",
    title: "এশিয়া কাপে বাংলাদেশের দুর্দান্ত জয়",
    slug: "bangladesh-asia-cup-win",
    excerpt: "শেষ ওভারের নাটকীয়তায় ৩ উইকেটের জয় তুলে নিল টাইগাররা।",
    category: findCategory("sports"),
    author: "ক্রীড়া প্রতিবেদক",
    publishedAt: "১ ঘণ্টা আগে",
    imageTone: "crimson",
  },
  {
    id: "spo-2",
    title: "ঘরোয়া ফুটবল লিগে চ্যাম্পিয়ন হলো আবাহনী",
    slug: "abahani-wins-domestic-league",
    excerpt: "মৌসুমের শেষ ম্যাচে প্রতিদ্বন্দ্বী দলকে ২-০ গোলে হারিয়ে শিরোপা নিশ্চিত।",
    category: findCategory("sports"),
    author: "ক্রীড়া প্রতিবেদক",
    publishedAt: "৫ ঘণ্টা আগে",
    imageTone: "navy",
  },
  {
    id: "spo-3",
    title: "সাফ চ্যাম্পিয়নশিপের দল ঘোষণা করল ফুটবল ফেডারেশন",
    slug: "saff-championship-squad-announced",
    excerpt: "নতুন কয়েকজন তরুণ খেলোয়াড়কে দলে জায়গা দেওয়া হয়েছে।",
    category: findCategory("sports"),
    author: "নিজস্ব প্রতিবেদক",
    publishedAt: "৮ ঘণ্টা আগে",
    imageTone: "slate",
  },
  {
    id: "spo-4",
    title: "অনূর্ধ্ব-১৯ ক্রিকেট বিশ্বকাপে সেমিফাইনালে বাংলাদেশ",
    slug: "u19-world-cup-semifinal",
    excerpt: "গ্রুপ পর্বে অপরাজিত থেকে শেষ চারে জায়গা করে নিল যুব দল।",
    category: findCategory("sports"),
    author: "ক্রীড়া প্রতিবেদক",
    publishedAt: "১২ ঘণ্টা আগে",
    imageTone: "amber",
  },
];

export const entertainmentArticles: Article[] = [
  {
    id: "ent-1",
    title: "ঈদে মুক্তি পাচ্ছে বছরের সবচেয়ে বড় বাজেটের চলচ্চিত্র",
    slug: "eid-release-biggest-budget-film",
    excerpt: "নির্মাতা জানিয়েছেন, দর্শকদের জন্য থাকছে ভিন্নধর্মী গল্প।",
    category: findCategory("entertainment"),
    author: "বিনোদন প্রতিবেদক",
    publishedAt: "৩ ঘণ্টা আগে",
    imageTone: "amber",
  },
  {
    id: "ent-2",
    title: "নতুন অ্যালবাম প্রকাশ করলেন জনপ্রিয় ব্যান্ড",
    slug: "popular-band-new-album",
    excerpt: "স্ট্রিমিং প্ল্যাটফর্মে প্রকাশের কয়েক ঘণ্টায় শীর্ষে উঠে আসে অ্যালবামটি।",
    category: findCategory("entertainment"),
    author: "বিনোদন প্রতিবেদক",
    publishedAt: "৬ ঘণ্টা আগে",
    imageTone: "crimson",
  },
  {
    id: "ent-3",
    title: "ওটিটি প্ল্যাটফর্মে আসছে বহুল প্রতীক্ষিত সিরিজ",
    slug: "ott-anticipated-series-release",
    excerpt: "প্রথম সিজনের সাফল্যের পর দ্বিতীয় সিজন নিয়ে দর্শকদের আগ্রহ তুঙ্গে।",
    category: findCategory("entertainment"),
    author: "নিজস্ব প্রতিবেদক",
    publishedAt: "৯ ঘণ্টা আগে",
    imageTone: "navy",
  },
  {
    id: "ent-4",
    title: "জাতীয় চলচ্চিত্র পুরস্কারের মনোনয়ন তালিকা প্রকাশ",
    slug: "national-film-award-nominations",
    excerpt: "সেরা চলচ্চিত্র বিভাগে লড়াই হবে পাঁচটি প্রশংসিত কাজের মধ্যে।",
    category: findCategory("entertainment"),
    author: "বিনোদন প্রতিবেদক",
    publishedAt: "১১ ঘণ্টা আগে",
    imageTone: "slate",
  },
];

export const videoArticles: Article[] = [
  {
    id: "vid-1",
    title: "সরাসরি: বাজেট অধিবেশনের গুরুত্বপূর্ণ মুহূর্ত",
    slug: "live-budget-session-highlights",
    excerpt: "সংসদের ভেতরের সরাসরি দৃশ্য।",
    category: findCategory("national"),
    author: "ভিডিও ডেস্ক",
    publishedAt: "১ ঘণ্টা আগে",
    imageTone: "navy",
    isVideo: true,
    videoDuration: "৪:১২",
  },
  {
    id: "vid-2",
    title: "ম্যাচ হাইলাইটস: শেষ ওভারের রোমাঞ্চ",
    slug: "match-highlights-final-over",
    excerpt: "একনজরে পুরো ম্যাচের সেরা মুহূর্তগুলো।",
    category: findCategory("sports"),
    author: "ভিডিও ডেস্ক",
    publishedAt: "২ ঘণ্টা আগে",
    imageTone: "crimson",
    isVideo: true,
    videoDuration: "৬:৪৫",
  },
  {
    id: "vid-3",
    title: "প্রতিবেদন: উপকূলীয় এলাকায় প্রস্তুতি পরিদর্শন",
    slug: "coastal-preparation-report",
    excerpt: "মাঠপর্যায়ের প্রস্তুতি নিয়ে বিস্তারিত প্রতিবেদন।",
    category: findCategory("environment"),
    author: "ভিডিও ডেস্ক",
    publishedAt: "৪ ঘণ্টা আগে",
    imageTone: "slate",
    isVideo: true,
    videoDuration: "৩:৩০",
  },
  {
    id: "vid-4",
    title: "সাক্ষাৎকার: নতুন উদ্যোক্তাদের সাফল্যের গল্প",
    slug: "entrepreneurs-success-interview",
    excerpt: "তরুণ উদ্যোক্তাদের অভিজ্ঞতা নিয়ে বিশেষ আয়োজন।",
    category: findCategory("business"),
    author: "ভিডিও ডেস্ক",
    publishedAt: "৭ ঘণ্টা আগে",
    imageTone: "amber",
    isVideo: true,
    videoDuration: "৮:০৯",
  },
];

export const galleryArticles: Article[] = [
  {
    id: "gal-1",
    title: "ছবিতে: শীতের সকালে গ্রামীণ জনজীবন",
    slug: "photo-story-winter-morning",
    excerpt: "",
    category: findCategory("lifestyle"),
    author: "ফটো ডেস্ক",
    publishedAt: "৩ ঘণ্টা আগে",
    imageTone: "amber",
  },
  {
    id: "gal-2",
    title: "ছবিতে: বৈশাখী মেলার রঙিন মুহূর্ত",
    slug: "photo-story-boishakhi-mela",
    excerpt: "",
    category: findCategory("lifestyle"),
    author: "ফটো ডেস্ক",
    publishedAt: "৫ ঘণ্টা আগে",
    imageTone: "crimson",
  },
  {
    id: "gal-3",
    title: "ছবিতে: নির্মাণাধীন এক্সপ্রেসওয়ের অগ্রগতি",
    slug: "photo-story-expressway-progress",
    excerpt: "",
    category: findCategory("national"),
    author: "ফটো ডেস্ক",
    publishedAt: "৮ ঘণ্টা আগে",
    imageTone: "navy",
  },
  {
    id: "gal-4",
    title: "ছবিতে: স্টেডিয়ামে সমর্থকদের উচ্ছ্বাস",
    slug: "photo-story-stadium-fans",
    excerpt: "",
    category: findCategory("sports"),
    author: "ফটো ডেস্ক",
    publishedAt: "১০ ঘণ্টা আগে",
    imageTone: "slate",
  },
];

export const trendingArticles: Article[] = [
  { ...politicsArticles[0], viewCount: 18400 },
  { ...sportsArticles[0], viewCount: 15200 },
  { ...heroArticle, viewCount: 12800 },
  { ...entertainmentArticles[0], viewCount: 9600 },
  { ...nationalArticles[1], viewCount: 8100 },
];
